name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  - name: Checkout Repo
    uses: actions/checkout@v3

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18

  - name: Install pnpm
    run: npm install -g pnpm

  - name: Install Dependencies
    run: pnpm install

  - name: Build Project
    env:
      VITE_GMAPS_API: ${{ secrets.VITE_GMAPS_API }}
      VITE_GMAPS_ID: ${{ secrets.VITE_GMAPS_ID }}
      VITE_CENTER: ${{ secrets.VITE_CENTER }}
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_DATABASE_URL: ${{ secrets.VITE_FIREBASE_DATABASE_URL }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
    run: pnpm build

  - name: Deploy to Firebase
    uses: w9jds/firebase-action@v2
    with:
      args: deploy
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

